baseURL: 'http://ivannoden.com/'
languageCode: 'en-gb'
title: 'Ivan Noden'

theme: "PaperMod"

params:
  defaultTheme: dark
  disableThemeToggle: true

  math: true

  env: production

  assets:
    favicon: "/favicon.ico"
    favicon16x16: "/favicon.ico"
    favicon32x32: "/favicon-32x32.png"
    apple_touch_icon: "apple-touch-icon.png"

  outputs:
    home:
      - HTML
      - RSS
      - JSON

  homeInfoParams:
    Title: Ivan Noden
    Content: Master's student in Mathematics at UCL.

  socialIcons:
    - name: "email"
      title: "Email"
      url: "mailto:ivan@ivannoden.com"
    - name: "rss"
      title: "RSS"
      url: "/index.xml"

menu:
  main:
    - identifier: talks
      name: Talks
      url: /tags/talks
      weight: 10
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 20
    - identifier: archive
      name: Archive
      url: /archive/
      weight: 30

markup:
  goldmark:
    extensions:
      passthrough:
        delimiters:
          block:
            -- \[
             - \]
            -- $$
             - $
          inline:
            -- \(
             - \)
            -- $
             - $
        enable: true
