baseURL: 'http://ivannoden.com/'
languageCode: 'en-gb'
title: 'Ivan Noden'

theme: "PaperMod"

params:
  defaultTheme: dark
  disableThemeToggle: true

  math: true

  env: production

  assets:
    favicon: "/favicon.ico"
    favicon16x16: "/favicon.ico"
    favicon32x32: "/favicon-32x32.png"
    apple_touch_icon: "apple-touch-icon.png"

  outputs:
    home:
      - HTML
      - RSS
      - JSON

  homeInfoParams:
    Title: Ivan Noden
    Content: PhD student at UCL, supervised by Dario Beraldo. Interested in algebraic geometry and geometric representation theory.

  socialIcons:
    - name: "email"
      title: "Email"
      url: "mailto:ivan.noden.21@ucl.ac.uk"
    - name: "rss"
      title: "RSS"
      url: "/index.xml"

  profileMode:
    enabled: true
    subtitle: PhD student at UCL, supervised by Dario Beraldo. Interested in algebraic geometry and geometric representation theory.
    buttons:
      - name: Papers and Preprints
        url: "/papers"

menu:
  main:
    - identifier: Papers and Preprints
      name: Papers and Preprints
      url: /papers
      weight: 9
#    - identifier: Talks
#      name: Talks
#      url: /tags/talks
#      weight: 10
#    - identifier: tags
#      name: Tags
#      url: /tags/
#      weight: 20
#    - identifier: archive
#      name: Archive
#      url: /archive/
#      weight: 30
#
markup:
  goldmark:
    extensions:
      passthrough:
        delimiters:
          block:
          - - \[
            - \]
          - - $$
            - $$
          inline:
          - - $
            - $
        enable: true

